[package]
name = "mini-lust-macros"
version = "0.1.0"
authors = ["ihciah <ihciah@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
darling = "0.13"
syn = "1"
proc-macro2 = "1"
quote = "1"
