[package]
name = "mini-lust-generator"
version = "0.1.0"
authors = ["ihciah <ihciah@gmail.com>"]
edition = "2018"

[dependencies]
thrift-parser = { path = "../thrift-parser" }
proc-macro2 = "1"
quote = "1"
thiserror = "1"
heck = "0.3"
